Update whitelist workflow to verify output files

diff --git a/.github/workflows/create_whitelist.yml b/.github/workflows/create_whitelist.yml
--- a/.github/workflows/create_whitelist.yml
+++ b/.github/workflows/create_whitelist.yml
@@ -19,19 +19,19 @@ jobs:
       - name: Create whitelists
         run: python3 scripts/whitelist-update.py
 
-      # - name: Verify output files exist
-      #   run: |
-      #     mkdir -p releases
-      #     if [ ! -f releases/aggregated-hosts.txt ] || [ ! -f releases/aggregated-dnsmasq.conf ] || [ ! -f releases/aggregated-adblock.txt ]; then
-      #       echo "Error: One or more output files are missing!"
-      #       exit 1
-      #     fi
+      - name: Verify output files exist
+        run: |
+          mkdir -p releases
+          if [ ! -f releases/whitelist.txt ]; then
+            echo "Error: One or more output files are missing!"
+            exit 1
+          fi
 
       - name: Commit outputs
         run: |
           git config user.name "github-actions[bot]"
           git config user.email "github-actions[bot]@users.noreply.github.com"
-          git add ./whitelist.txt
+          git add releases/
           # only commit if there are changes
-          git diff --quiet && echo "No changes to commit" || git commit -m "chore: update aggregated lists"
+          git diff --quiet && echo "No changes to commit" || git commit -m "chore: update whitelist lists"
           git push
